# databases:
#   - name: postgres
#     ipAllowList: []
#     # databaseName: product_test_db
#     # user: demo

# services:
#   - type: web
#     name: demo
#     env: ruby
#     buildCommand: "./bin/render-build.sh"
#     startCommand: bundle exec rails s
#     envVars:
#       - key: RAILS_MASTER_KEY
#         sync: false 
#       - key: DATABASE_URL
#         fromDatabase:
#           name: postgres
#           property: connectionString
#   - type: redis
#     name: redis
#     ipAllowList: []
#     plan: free
#     maxmemoryPolicy: noeviction

databases:
  - name: postgres
    databaseName: product_crud
    user: postgres
    plan: free
services:
  - type: web
    name: postgres
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2