default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["RAILS_DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  idle_timeout: <%= ENV["RAILS_IDLE_CONNECTION"] ||  60 %>
  port: <%= ENV['RAILS_DATABASE_PORT'] || 5432 %>


development:
  <<: *default
  adapter: postgresql
  database: <%= ENV['DATABASE'] || 'product_dev_db' %>
  username: <%= ENV['DATABASE_USER'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'password' %>
  host: <%= ENV['ATABASE_HOSTNAME'] || 'localhost' %>
  port: 5432

test:
  <<: *default
  adapter: postgresql
  database: <%= ENV['DATABASE'] || 'product_test_db' %>
  username: <%= ENV['DATABASE_USER'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'password' %>
  host: <%= ENV['DATABASE_HOSTNAME'] || 'localhost' %>
  port: 5432

production:
  <<: *default
  adapter: postgresql
  database: <%= ENV['DATABASE'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOSTNAME'] %>
  port: 5432